### ISSUE TITLE
ava.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by hellodonj** [asdfqwrasdf/ArcFaceDemo#100]
FATAL EXCEPTION: main
                                                                                 Process: com.winning.djj.facerecognition, PID: 12109
                                                                                 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.winning.djj.facerecognition-1/base.apk"],nativeLibraryDirectories=[/data/app/com.winning.djj.facerecognition-1/lib/arm, /data/app/com.winning.djj.facerecognition-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libmpbase.so"
                                                                                     at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                                     at java.lang.System.loadLibrary(System.java:1076)
                                                                                     at com.arcsoft.facerecognition.AFR_FSDKEngine.<clinit>(AFR_FSDKEngine.java:25)
                                                                                     at com.winning.djj.facerecognition.FaceDB.<init>(FaceDB.java:62)
                                                                                     at com.winning.djj.facerecognition.Application.onCreate(Application.java:24)
                                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4857)
                                                                                     at android.app.ActivityThread.access$1800(ActivityThread.java:153)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:157)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5684)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)

**Comment by hellodonj** [comment]
sourceSets.main {
            jniLibs.srcDirs = ['libs']
        }
找不到.so文件，在gradle中加入上述代码！

**Comment by asdfqwrasdf** [comment]
Thanks for your information.
