### ISSUE TITLE
运行项目报错

### ISSUE THREAD

**Issue by HuangZhiwei97** [asdfqwrasdf/ArcFaceDemo#103]
E/linker: library "/system/lib64/libmpbase.so" ("/system/lib64/libmpbase.so") needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.example.administrator.encryptionsoftware-fELPAj9CAvDLfFKUFgyufQ==/lib/arm64:/data/app/com.example.administrator.encryptionsoftware-fELPAj9CAvDLfFKUFgyufQ==/base.apk!/lib/arm64-v8a:/data/app/com.example.administrator.encryptionsoftware-fELPAj9CAvDLfFKUFgyufQ==/split_lib_dependencies_apk.apk!/lib/arm64-v8a:/data/app/com.example.administrator.encryptionsoftware-fELPAj9CAvDLfFKUFgyufQ==/split_lib_slice_0_apk.apk!/lib/arm64-v8a:/data/app/com.example.administrator.encryptionsoftware-fELPAj9CAvDLfFKUFgyufQ==/split_lib_slice_1_apk.apk!/lib/arm64-v8a:/data/app/com.example.administrator.encryptionsoftware-fELPAj9CAvDLfFKUFgyufQ==/split_lib_slice_2_apk.apk!/lib/arm64-v8a:/data/app/com.example.administrator.encryptionsoftware-fELPAj9CAvDLfFKUFgyufQ==/split_lib_slice_3_apk.a
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.administrator.encryptionsoftware, PID: 4112
                  java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libmpbase.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
                      at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
                      at java.lang.System.loadLibrary(System.java:1657)
                      at com.arcsoft.facetracking.AFT_FSDKEngine.<clinit>(AFT_FSDKEngine.java:26)
                      at com.example.administrator.encryptionsoftware.ui.activity.DetecterFaceActivity.<init>(DetecterFaceActivity.java:68)
                      at java.lang.Class.newInstance(Native Method)
                      at android.app.Instrumentation.newActivity(Instrumentation.java:1175)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2688)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2875)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1604)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6618)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)
I/Process: Sending signal. PID: 4112 SIG: 9
Application terminated.

**Comment by asdfqwrasdf** [comment]
ref #11 #96 #97

**Comment by HuangZhiwei97** [comment]
> ref #11 #96 #97

what means？

**Comment by asdfqwrasdf** [comment]
V1.0 not support 64bit
