### ISSUE TITLE
安卓环境运行出错，求教

### ISSUE THREAD

**Issue by TaowzzZ** [asdfqwrasdf/ArcFaceDemo#16]
安卓环境，三星S4，android4.4，打开app崩溃，报错如下：

11-13 21:29:33.597 7106-7106/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.ExceptionInInitializerError
                                                     at com.arcsoft.sdk_demo.FaceDB.<init>(FaceDB.java:54)
                                                     at com.arcsoft.sdk_demo.Application.onCreate(Application.java:22)
                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4567)
                                                     at android.app.ActivityThread.access$1400(ActivityThread.java:151)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5293)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.UnsatisfiedLinkError: Couldn't load mpbase from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.arcsoft.sdk_demo-1.apk,libraryPath=/data/app-lib/com.arcsoft.sdk_demo-1]: findLibrary returned null
                                                     at java.lang.Runtime.loadLibrary(Runtime.java:365)
                                                     at java.lang.System.loadLibrary(System.java:535)
                                                     at com.arcsoft.facerecognition.AFR_FSDKEngine.<clinit>(AFR_FSDKEngine.java:25)
                                                     at com.arcsoft.sdk_demo.FaceDB.<init>(FaceDB.java:54) 
                                                     at com.arcsoft.sdk_demo.Application.onCreate(Application.java:22) 
                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017) 
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4567) 
                                                     at android.app.ActivityThread.access$1400(ActivityThread.java:151) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5293) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                     at dalvik.system.NativeStart.main(Native Method) 

请问这是什么原因？

**Comment by gqjjqg** [comment]
Caused by: java.lang.UnsatisfiedLinkError: Couldn't load mpbase from loader

缺少mpbase.so，建议仔细阅读readme，按readme操作
