### ISSUE TITLE
融入项目中，混淆打包正式后找不到libArcSoft_FREngine.so，测试没有问题

### ISSUE THREAD

**Issue by hunimeizi** [asdfqwrasdf/ArcFaceDemo#23]
为什么融入我们项目中，混淆打包后，提示找不到该libArcSoft_FREngine.so，而测试环境没有问题
 java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.libolian.huacaiyou-1/lib/arm/libArcSoft_FREngine.so"
                                                   at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                   at java.lang.System.loadLibrary(System.java:988)
                                                   at com.arcsoft.facerecognition.AFR_FSDKEngine.<clinit>(AFR_FSDKEngine.java:26)
                                                   at com.libolian.huacaiyou.view.d.<init>(FaceDB.java:49)
                                                   at com.libolian.huacaiyou.base.BaseApplication.onCreate(BaseApplication.java:60)
                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4963)
                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:200)
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
                                                   at android.os.Handler.dispatchMessage(Handler.java:111)
                                                   at android.os.Looper.loop(Looper.java:194)
                                                   at android.app.ActivityThread.main(ActivityThread.java:5786)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1042)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
-

**Comment by asdfqwrasdf** [comment]
不要混淆sdk的jar，看样子可能是包名加载失败
