### ISSUE TITLE
 打包运行错误， java.lang.UnsatisfiedLinkError 

### ISSUE THREAD

**Issue by synchroni** [asdfqwrasdf/ArcFaceDemo#30]
12-12 20:20:44.887 22763-22763/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.jzg.buildworker, PID: 22763
                                                   java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.jzg.buildworker-1/lib/arm/libArcSoft_FREngine.so"
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                       at java.lang.System.loadLibrary(System.java:1076)
                                                       at com.arcsoft.facerecognition.AFR_FSDKEngine.<clinit>(Unknown Source)
                                                       at com.jzg.buildworker.kit.g.<init>(Unknown Source)
                                                       at com.jzg.buildworker.JzgApplication.onCreate(Unknown Source)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4765)
                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:153)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1436)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5524)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:740)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)

用了网上N种方法也没有用，就是说找不到 libArcSoft_FREngine.so  但是我打出来的包lib中有，这怎么解？

**Comment by asdfqwrasdf** [comment]
/data/app/com.jzg.buildworker-1/lib/arm/libArcSoft_FREngine.so

路径都有了,adb shell一下,看看是不是缺了so, 八成 就是你的apk打包有问题.

**Comment by synchroni** [comment]
刚才我已解决了，这个用了我一天解决的问题，知道原因后我都想吐血，，重要事要说三遍，打包的时候不要混淆、不要混淆、不要混淆！！！！！
