### ISSUE TITLE
找不到文件face.txt

### ISSUE THREAD

**Issue by tylorte** [asdfqwrasdf/ArcFaceDemo#32]
运行demo时，提示找不到face.txt文件，
报错的代码在FileInputStream fs = new FileInputStream(mDBPath + "/face.txt");

以下是日志
12-19 10:23:35.512 7679-7703/com.arcsoft.sdk_demo W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.arcsoft.sdk_demo/cache/face.txt: open failed: ENOENT (No such file or directory)
12-19 10:23:35.512 7679-7703/com.arcsoft.sdk_demo W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:409)
12-19 10:23:35.512 7679-7703/com.arcsoft.sdk_demo W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:78)
12-19 10:23:35.512 7679-7703/com.arcsoft.sdk_demo W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:105)
12-19 10:23:35.512 7679-7703/com.arcsoft.sdk_demo W/System.err:     at com.arcsoft.sdk_demo.FaceDB.loadInfo(FaceDB.java:92)
12-19 10:23:35.520 7679-7703/com.arcsoft.sdk_demo W/System.err:     at com.arcsoft.sdk_demo.FaceDB.loadFaces(FaceDB.java:119)
12-19 10:23:35.520 7679-7703/com.arcsoft.sdk_demo W/System.err:     at com.arcsoft.sdk_demo.PermissionAcitivity$1.run(PermissionAcitivity.java:89)
12-19 10:23:35.520 7679-7703/com.arcsoft.sdk_demo W/System.err:     at java.lang.Thread.run(Thread.java:841)

请问如何解决这个问题呢

**Comment by tylorte** [comment]
也许我找到方法了，感谢
