### ISSUE TITLE
Bug in demo code

### ISSUE THREAD

**Issue by overlook1234** [asdfqwrasdf/ArcFaceDemo#33]
I got error when I try the demo code.
In PermissionActivity.java:

public void startActiviy() {

mProgressDialog.show();

}

01-01 17:06:18.326 21592-21592/cn.com.hotcent.testarcface E/WindowManager: android.view.WindowLeaked: Activity cn.com.hotcent.testarcface.PermissionAcitivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{8e50da3 V.E...... R......D 0,0-684,322} that was originally added here
                                                                               at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
                                                                               at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:302)
                                                                               at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
                                                                               at android.app.Dialog.show(Dialog.java:322)
                                                                               at cn.com.hotcent.testarcface.PermissionAcitivity.startActiviy(PermissionAcitivity.java:84)
                                                                               at cn.com.hotcent.testarcface.PermissionAcitivity.onCreate(PermissionAcitivity.java:50)
                                                                               at android.app.Activity.performCreate(Activity.java:6303)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2402)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
                                                                               at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by asdfqwrasdf** [comment]
Please give the source line number of this issue.
My test device is android 5.0. Not found this issue.

**Comment by overlook1234** [comment]
I got the error when I use your source code(java, layout, manifest) into a new android project.

**Comment by asdfqwrasdf** [comment]
My advice: double check the view object for dialog.
Your log tell me, the dialog view has been duplicated added.
