### ISSUE TITLE
安装成功后闪退

### ISSUE THREAD

**Issue by kong222** [asdfqwrasdf/ArcFaceDemo#41]
加了sourceSets.main {
            jniLibs.srcDirs = ['libs']
        }
也没有用

**Comment by kong222** [comment]
01-20 15:35:00.247 25819-25819/? I/art: Late-enabling -Xcheck:jni
01-20 15:35:00.256 25819-25819/? D/TidaProvider: TidaProvider()
01-20 15:35:00.292 25819-25819/com.arcsoft.sdk_demo E/linker: library "/vendor/lib/libmpbase.so" ("/system/vendor/lib/libmpbase.so") needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.arcsoft.sdk_demo-1/lib/arm:/data/app/com.arcsoft.sdk_demo-1/base.apk!/lib/armeabi-v7a", permitted_paths="/data:/mnt/expand:/data/data/com.arcsoft.sdk_demo"]
01-20 15:35:00.293 25819-25819/com.arcsoft.sdk_demo D/AndroidRuntime: Shutting down VM
01-20 15:35:00.293 25819-25819/com.arcsoft.sdk_demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.arcsoft.sdk_demo, PID: 25819
                                                                      java.lang.UnsatisfiedLinkError: dlopen failed: library "/vendor/lib/libmpbase.so" needed or dlopened by "/system/lib/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
                                                                          at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                                                          at java.lang.System.loadLibrary(System.java:1530)
                                                                          at com.arcsoft.facerecognition.AFR_FSDKEngine.<clinit>(AFR_FSDKEngine.java:25)
                                                                          at com.arcsoft.sdk_demo.FaceDB.<init>(FaceDB.java:55)
                                                                          at com.arcsoft.sdk_demo.Application.onCreate(Application.java:22)
                                                                          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5531)
                                                                          at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:163)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6368)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
01-20 15:35:00.304 25819-25819/com.arcsoft.sdk_demo I/Process: Sending signal. PID: 25819 SIG: 9

**Comment by asdfqwrasdf** [comment]
目测这个可能是android系统的新特性导致不允许直接加载外部的 so了。
建议提交bug 到[论坛](http://www.arcsoft.com.cn/bbs/)，我这边解决不了。

**Comment by kong222** [comment]
http://blog.csdn.net/shikangkai/article/details/51610997  
用这个方法解决了
