### ISSUE TITLE
集成报错

### ISSUE THREAD

**Issue by kulong51** [asdfqwrasdf/ArcFaceDemo#68]
Process: com.arcsoft.sdk_demo, PID: 11738
    java.lang.UnsatisfiedLinkError: Couldn't load mpbase from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/mnt/asec/com.arcsoft.sdk_demo-2/pkg.apk"],nativeLibraryDirectories=[/mnt/asec/com.arcsoft.sdk_demo-2/lib, /vendor/lib, /system/lib]]]: findLibrary returned null
        at java.lang.Runtime.loadLibrary(Runtime.java:365)
        at java.lang.System.loadLibrary(System.java:526)
        at com.arcsoft.facerecognition.AFR_FSDKEngine.<clinit>(AFR_FSDKEngine.java:25)
        at com.arcsoft.sdk_demo.FaceDB.<init>(FaceDB.java:55)
        at com.arcsoft.sdk_demo.Application.onCreate(Application.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1009)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4624)
        at android.app.ActivityThread.access$1500(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5378)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by kulong51** [comment]
已解决
