### ISSUE TITLE
 java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by LAzyOnline** [asdfqwrasdf/ArcFaceDemo#7]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.arcsoft.sdk_demo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.arcsoft.sdk_demo-2/lib/arm, /data/app/com.arcsoft.sdk_demo-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libmpbase.so"
                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:379)
                                                                          at java.lang.System.loadLibrary(System.java:1086)
                                                                          at com.arcsoft.facerecognition.AFR_FSDKEngine.<clinit>(AFR_FSDKEngine.java:25)
                                                                          at com.arcsoft.sdk_demo.FaceDB.<init>(FaceDB.java:54)
                                                                          at com.arcsoft.sdk_demo.Application.onCreate(Application.java:20)
                                                                          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4793)
                                                                          at android.app.ActivityThread.access$1600(ActivityThread.java:165)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:150)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

您好，华为荣耀6的机型出现couldn't find 'libmpbase.so'的问题，系统：Android6.0 ，CPU：麒麟935

**Comment by LAzyOnline** [comment]
直接将Demo从Git上clone后，只将代码中的Appid以及各种key值替换，其余未修改任何文件。同时也检查了armeabi和armebi-v7a包的文件是一致的（但是和SDK的文件不对应，不知道是不是Demo中的so文件改了名字了）

**Comment by LAzyOnline** [comment]
HTC M9PW同样的错误，系统：Android6.0，CPU：联发科6795

**Comment by LAzyOnline** [comment]
sorry~~原来还得将SDK的so文件导入过去....现在导入进去就好了...
