### ISSUE TITLE
demo 各种挂掉

### ISSUE THREAD

**Issue by kulong51** [asdfqwrasdf/ArcFaceDemo#77]
问题1：
  Process: com.arcsoft.sdk_demo, PID: 12756
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.arcsoft.sdk_demo/com.arcsoft.sdk_demo.RegisterActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
        at android.app.ActivityThread.access$800(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5378)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
        at com.arcsoft.sdk_demo.RegisterActivity.onCreate(RegisterActivity.java:88)
        at android.app.Activity.performCreate(Activity.java:5472)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
        at android.app.ActivityThread.access$800(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:5378) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645) 
        at dalvik.system.NativeStart.main(Native Method) 

问题2：
05-12 11:01:13.514 13338-13338/com.arcsoft.sdk_demo E/CameraSurfaceView: camera start fail!
05-12 11:01:13.551 13338-13338/com.arcsoft.sdk_demo E/InputEventReceiver: Exception dispatching input event.
05-12 11:01:13.551 13338-13338/com.arcsoft.sdk_demo E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
05-12 11:01:13.566 13338-13601/com.arcsoft.sdk_demo E/ATC.: link failed
    Error linking program: L0100 GLSL allows exactly two attached shaders (one of each type) per program
    link failed -> out
05-12 11:01:13.583 13338-13338/com.arcsoft.sdk_demo E/MessageQueue-JNI: java.lang.NullPointerException
        at com.guo.android_extend.tools.CameraHelper.touchFocus(CameraHelper.java:81)
        at com.arcsoft.sdk_demo.DetecterActivity.onTouch(DetecterActivity.java:380)
        at android.view.View.dispatchTouchEvent(View.java:7795)
        at com.guo.android_extend.widget.ExtGLSurfaceView.dispatchTouchEvent(ExtGLSurfaceView.java:159)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2162)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1594)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2526)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2110)
        at android.view.View.dispatchPointerEvent(View.java:7996)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4449)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4320)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3840)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3890)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3859)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3966)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3867)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4023)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3840)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3890)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3859)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3867)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3840)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6181)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6161)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6115)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6311)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:138)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5378)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
        at dalvik.system.NativeStart.main(Native Method)
05-12 11:01:13.591 13338-13338/com.arcsoft.sdk_demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.arcsoft.sdk_demo, PID: 13338
    java.lang.NullPointerException
        at com.guo.android_extend.tools.CameraHelper.touchFocus(CameraHelper.java:81)
        at com.arcsoft.sdk_demo.DetecterActivity.onTouch(DetecterActivity.java:380)
        at android.view.View.dispatchTouchEvent(View.java:7795)
        at com.guo.android_extend.widget.ExtGLSurfaceView.dispatchTouchEvent(ExtGLSurfaceView.java:159)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2162)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1594)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2526)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2110)
        at android.view.View.dispatchPointerEvent(View.java:7996)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4449)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4320)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3840)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3890)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3859)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3966)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3867)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4023)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3840)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3890)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3859)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3867)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3840)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6181)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6161)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6115)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6311)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:138)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5378)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
        at dalvik.system.NativeStart.main(Native Method)
问题3：
05-12 11:02:57.262 14957-14957/com.arcsoft.sdk_demo E/FrameHelper: FPS = 17
05-12 11:02:57.925 14957-14957/com.arcsoft.sdk_demo E/FrameHelper: FPS = 16
05-12 11:02:58.586 14957-14957/com.arcsoft.sdk_demo E/FrameHelper: FPS = 16
05-12 11:02:59.246 14957-14957/com.arcsoft.sdk_demo E/FrameHelper: FPS = 16
05-12 11:02:59.912 14957-14957/com.arcsoft.sdk_demo E/FrameHelper: FPS = 16
05-12 11:03:00.570 14957-14957/com.arcsoft.sdk_demo E/FrameHelper: FPS = 16
05-12 11:03:01.230 14957-14957/com.arcsoft.sdk_demo E/FrameHelper: FPS = 16
05-12 11:03:01.890 14957-14957/com.arcsoft.sdk_demo E/FrameHelper: FPS = 16
05-12 11:03:02.555 14957-14957/com.arcsoft.sdk_demo E/FrameHelper: FPS = 16
05-12 11:03:04.323 14957-14957/com.arcsoft.sdk_demo E/InputEventReceiver: Exception dispatching input event.
05-12 11:03:04.323 14957-14957/com.arcsoft.sdk_demo E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
05-12 11:03:04.330 14957-14957/com.arcsoft.sdk_demo E/MessageQueue-JNI: java.lang.RuntimeException: getParameters failed (empty parameters)
        at android.hardware.Camera.native_getParameters(Native Method)
        at android.hardware.Camera.getParameters(Camera.java:2681)
        at com.guo.android_extend.tools.CameraHelper.touchFocus(CameraHelper.java:81)
        at com.arcsoft.sdk_demo.DetecterActivity.onTouch(DetecterActivity.java:380)
        at android.view.View.dispatchTouchEvent(View.java:7795)
        at com.guo.android_extend.widget.ExtGLSurfaceView.dispatchTouchEvent(ExtGLSurfaceView.java:159)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2162)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1594)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2526)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2110)
        at android.view.View.dispatchPointerEvent(View.java:7996)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4449)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4320)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3840)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3890)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3859)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3966)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3867)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4023)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3840)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3890)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3859)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3867)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3840)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6181)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6161)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6115)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6311)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:138)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5378)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
        at dalvik.system.NativeStart.main(Native Method)
05-12 11:03:04.333 14957-14957/com.arcsoft.sdk_demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.arcsoft.sdk_demo, PID: 14957
    java.lang.RuntimeException: getParameters failed (empty parameters)
        at android.hardware.Camera.native_getParameters(Native Method)
        at android.hardware.Camera.getParameters(Camera.java:2681)
        at com.guo.android_extend.tools.CameraHelper.touchFocus(CameraHelper.java:81)
        at com.arcsoft.sdk_demo.DetecterActivity.onTouch(DetecterActivity.java:380)
        at android.view.View.dispatchTouchEvent(View.java:7795)
        at com.guo.android_extend.widget.ExtGLSurfaceView.dispatchTouchEvent(ExtGLSurfaceView.java:159)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2327)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2162)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1594)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2526)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2110)
        at android.view.View.dispatchPointerEvent(View.java:7996)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4449)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4320)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3840)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3890)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3859)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3966)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3867)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4023)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3840)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3890)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3859)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3867)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3840)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6181)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6161)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6115)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6311)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:138)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5378)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by asdfqwrasdf** [comment]
问题1，可能图像路径不对，导致解码bitmap空指针
问题2，相机打开失败
问题3，触摸对焦时，相机参数获取失败

**Comment by kulong51** [comment]
demo 未做任何修改，使用过程中出现以上各种挂掉问题

**Comment by asdfqwrasdf** [comment]
请看readme，如何报告问题

**Comment by kulong51** [comment]
谢谢，已经修复
