### ISSUE TITLE
 列表溢出异常java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by Weigaa** [asdfqwrasdf/ArcFaceDemo#88]
[Demo程序在安装过程没有问题，注册照片也没有问题，但是识别的时候无法识别并提示已停止，观察logcat发现有如下提示：
E/AndroidRuntime: FATAL EXCEPTION: Thread-2676
    Process: com.arcsoft.sdk_demo, PID: 11887
    java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.arcsoft.sdk_demo.DetecterActivity$FRAbsLoop.loop(DetecterActivity.java:139)
        at com.guo.android_extend.java.AbsLoop.run(AbsLoop.java:20)
请问这是什么问题？

**Comment by Weigaa** [comment]
139和140行ages可能发生了溢出异常，但不清楚原因，注释掉这两行和下面用到ages的语句就可以用了，我想知道原因是什么呢？

**Comment by Weigaa** [comment]
找了一下午找到原因了，复制粘贴密钥的时候多复制了一个空格
